### ISSUE TITLE
Syntax Error - JumpCounter.lua ln.35

### ISSUE THREAD

**Issue by alabashtaur** [ajanke/JumpCounter#1]
Love this add-on but since moving this to my TitanBar it throws a syntax error all the time. I have swatter catching it now but it would be nice to get a fix in place. I tried to do a pull request but I can't branch the project. Can you please fix the following? 

Current Syntax -
    JumpCounter.lua:35 GameTooltip.Show()

Should be - 
    JumpCounter.llua:35 GameTooltip:Show()

**Comment by ajanke** [comment]
Sorry, I haven't played Classic in a while. I just hopped on and tried both Titan Panel and Chocolate Bar and neither reported any errors for me which is weird since the API does specify a colon rather than a dot.

In any case I updated it, thanks for the report!
